# Generated by Django 5.2.9 on 2025-12-16 15:40

import app.models
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('destaque', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Compra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_compra', models.DateTimeField(auto_now_add=True)),
                ('valor_total', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('finalizada', 'Finalizada'), ('cancelado', 'Cancelado')], default='pendente', max_length=20)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='minhas_compras', to=settings.AUTH_USER_MODEL, verbose_name='Client')),
            ],
        ),
        migrations.CreateModel(
            name='FotoPerfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto_perfil', models.ImageField(blank=True, default='fotos-usuarios/bobas.webp', null=True, upload_to='fotos-usuarios/')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='minha_foto', to=settings.AUTH_USER_MODEL, verbose_name='Client')),
            ],
        ),
        migrations.CreateModel(
            name='Jogo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('preco', models.DecimalField(decimal_places=2, max_digits=8)),
                ('descricao', models.TextField()),
                ('banner', models.BooleanField(default=False)),
                ('pre_lancamento', models.BooleanField(default=False)),
                ('deletado', models.BooleanField(default=False)),
                ('autoria', models.CharField(default='Desconhecido', max_length=200)),
                ('lancamento', models.DateField(default=django.utils.timezone.now)),
                ('desconto', models.IntegerField(blank=True, default=0, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('plataforma', models.CharField(choices=[('pc', 'PC')], default='pc', max_length=20)),
                ('icone', models.ImageField(blank=True, default='icones/birdgame.webp', null=True, upload_to='icones/')),
                ('categoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jogos', to='app.categoria')),
            ],
        ),
        migrations.CreateModel(
            name='ItemCompra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.PositiveIntegerField(default=1)),
                ('preco_unitario', models.DecimalField(decimal_places=2, max_digits=8)),
                ('nome_snapshot', models.CharField(blank=True, max_length=200)),
                ('compra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='app.compra')),
                ('jogo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.jogo')),
            ],
            options={
                'unique_together': {('compra', 'jogo')},
            },
        ),
        migrations.AddField(
            model_name='compra',
            name='jogos',
            field=models.ManyToManyField(related_name='compras', through='app.ItemCompra', to='app.jogo'),
        ),
        migrations.CreateModel(
            name='ImagemExtra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.ImageField(upload_to=app.models.upload_to_imagem)),
                ('ordem', models.IntegerField(default=0, help_text='Ordem de exibição (0 = primeiro)', validators=[django.core.validators.MinValueValidator(0)])),
                ('jogo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagens_extras', to='app.jogo')),
            ],
            options={
                'verbose_name': 'Imagem Extra',
                'verbose_name_plural': 'Imagens Extras',
                'ordering': ['ordem'],
                'unique_together': {('jogo', 'ordem')},
            },
        ),
    ]
