# Generated by Django 5.2.9 on 2025-12-10 22:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Usuario',
            new_name='Jogos',
        ),
    ]
