# Generated by Django 5.2.9 on 2025-12-10 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_rename_usuario_jogos'),
    ]

    operations = [
        migrations.CreateModel(
            name='Jogo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('preco', models.DecimalField(decimal_places=2, max_digits=8)),
                ('descricao', models.TextField()),
                ('icone', models.ImageField(upload_to='icones/')),
            ],
        ),
        migrations.DeleteModel(
            name='Jogos',
        ),
    ]
