# Generated by Django 5.2.9 on 2025-12-11 23:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_categoria_jogo_categoria_compra'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='compra',
            name='jogos',
        ),
        migrations.AddField(
            model_name='compra',
            name='jogo',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='compras', to='app.jogo'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='compra',
            name='quantidade',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='compra',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='minhas_compras', to=settings.AUTH_USER_MODEL),
        ),
    ]
