# Generated by Django 5.2.9 on 2025-12-12 17:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_remove_compra_jogo_remove_compra_quantidade_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='compra',
            name='jogos',
            field=models.ManyToManyField(related_name='compras', through='app.ItemCompra', to='app.jogo'),
        ),
        migrations.AlterField(
            model_name='compra',
            name='status',
            field=models.CharField(choices=[('pendente', 'Pendente'), ('aprovado', 'Aprovado'), ('cancelado', 'Cancelado'), ('entregue', 'Entregue')], default='carrinho', max_length=20),
        ),
        migrations.AlterField(
            model_name='itemcompra',
            name='jogo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.jogo'),
        ),
    ]
