# Generated by Django 5.2.9 on 2025-12-12 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_compra_jogos_alter_compra_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='destaque',
            field=models.BooleanField(default=False),
        ),
    ]
